export const book = [
  {
    id: 1,
    isbn: "12ax3",
    name: "B",
    author: "Ahmad  Hamdan",
    price: 20,
    rent_price: 5,
    latest_process: 30,
    active: true,
    packages: ["Ultimate Book Package", "Limited Edition", "Limited Edition1"],
  },
  {
    id: 2,
    isbn: "5hax3",
    name: "C",
    author: "Lyn Rammel",
    price: 30,
    rent_price: 7,
    latest_process: 31,
    active: true,
    packages: ["Ultimate Book Package", "Limited Edition"],
  },
  {
    id: 3,
    isbn: "65av2",
    name: "A",
    author: "Zainab Hjeze",
    price: 40,
    rent_price: 9,
    latest_process: 32,
    active: true,
    packages: ["Ultimate Book Package", "Limited Edition1"],
  },
];
export const history = [
  {
    id: 1,
    isbn: "12ax3",
    name: "A",
    author: "Ahmad  Hamdan",
    price: 20,
    rent_price: 5,
    active: true,
    process: 1,
    packages: ["Ultimate Book Package", "Limited Edition"],
  },
  {
    id: 1,
    isbn: "12ax3",
    name: "C",
    author: "Ahmad  Hamdan",
    price: 18,
    rent_price: 4,
    active: false,
    process: 32,
    packages: ["Ultimate Book Package", "Limited Edition"],
  },
  {
    id: 1,
    isbn: "12ax3",
    name: "D",
    author: "Ahmad  Hamdan",
    price: 23,
    rent_price: 7,
    active: false,
    process: 33,
    packages: ["Limited Edition"],
  },
  {
    id: 1,
    isbn: "12ax3",
    name: "E",
    author: "Ahmad  Hamdan",
    price: 30,
    rent_price: 8,
    active: false,
    process: 34,
    packages: ["Ultimate Book Package", "Limited Edition"],
  },
  {
    id: 2,
    isbn: "12ax3",
    name: "E",
    author: "Ahmad  Hamdan",
    price: 30,
    rent_price: 8,
    active: false,
    process: 1,
    packages: ["Ultimate Book Package", "Limited Edition"],
  },
  {
    id: 3,
    isbn: "12ax3",
    name: "F",
    author: "ALI  Hamdan",
    price: 50,
    rent_price: 18,
    active: false,
    process: 1,
    packages: ["Ultimate Book Package", "Limited Edition"],
  },
];

export const Process = [
  {
    id: 1,
    name: "process1",
    effectivedate: "2024-10-12",
    active: "true",
  },
  {
    id: 2,
    name: "process2",
    effectivedate: "2024-10-13",
    active: "true",
  },
  {
    id: 3,
    name: "process3",
    effectivedate: "2024-10-14",
    active: "true",
  },
];
