export const ProcessData = [
  {
    id: 1,
    name: "process 1",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 2,
    name: "process 2",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 3,
    name: "process 3",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 4,
    name: "process 4",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 5,
    name: "process 5",
    effectiveDate: "2024-7-31",
    active: true,
  },
  {
    id: 6,
    name: "process 1",
    effectiveDate: "2024-7-31",
    active: true,
  },
  {
    id: 7,
    name: "process 2",
    effectiveDate: "2024-7-31",
    active: true,
  },
  {
    id: 8,
    name: "process 3",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 9,
    name: "process 4",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 10,
    name: "process 5",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 11,
    name: "process 1",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 12,
    name: "process 2",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 13,
    name: "process 3",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 14,
    name: "process 4",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 15,
    name: "process 5",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 16,
    name: "process 1",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 17,
    name: "process 2",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 18,
    name: "process 3",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 19,
    name: "process 4",
    effectiveDate: "2024-7-31",
    active: false,
  },
  {
    id: 20,
    name: "process 5",
    effectiveDate: "2024-7-31",
    active: true,
  },
];
